---

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - '**/*_spec.rb'

Metrics/ModuleLength:
  Max: 300

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20
